[profile.default]
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
devnet = "https://network.ambrosus-dev.io/"
testnet = "https://network.ambrosus-test.io"
mainnet = "https://network.ambrosus.io"